/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:275c5ed7315b2f788e1f1d3b5d32e818:56dbdf020393faf7f424d82c8b83a4df:a4ea2fbda0ea174866bf6a7d218d7160$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class Sprites
	{
		public const string Bullet = "Bullet";
		public const string Dirt = "Dirt";
		public const string MetalWall = "MetalWall";
		public const string Placeholder = "Placeholder";
		public const string Player = "Player";
		public const string White = "White";
	}
}